databases:
  - name: peachcosmecollege_DB
    databaseName: peachcosmecollege_db
    user: peachcosmecollege
    region: singapore

services:
  - type: web
    name: pechcosmecollege
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: peachcosmecollege
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false